# Generated by Django 4.2.4 on 2023-10-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamaGochi_Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='information',
            table='Information',
        ),
    ]
