# Generated by Django 4.2.4 on 2023-10-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamaGochi_Home', '0002_alter_information_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='information',
            table='information',
        ),
    ]
